# permissions for end users to edit managedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: managed-cluster
    app.kubernetes.io/part-of: managed-cluster
    app.kubernetes.io/managed-by: kustomize
  name: managedcluster-editor-role
rules:
- apiGroups:
  - monitoring.cloudsya.com
  resources:
  - managedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cloudsya.com
  resources:
  - managedclusters/status
  verbs:
  - get
