# permissions for end users to edit portscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: port-scan
    app.kubernetes.io/part-of: port-scan
    app.kubernetes.io/managed-by: kustomize
  name: managedcluster-editor-role
rules:
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - portscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - portscans/status
  verbs:
  - get
